# Generated by Django 3.2 on 2022-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_color_size_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
