# Generated by Django 4.1 on 2022-08-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "fashion",
            "0015_rename_stripe_payment_intent_orderplaced_razorpay_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fashion.customer",
            ),
            preserve_default=False,
        ),
    ]
